### PR TITLE
Updated: Fe.Grant, Fe.Sent  |  Added: Fe.Deduct

### PR DESCRIPTION
**Pull request by OdiumxXx**
- Updated Grant & Set to getShortenedAccount as is done with Send/Balance
- Added Fe.Deduct Command (Deducts Fe from a player)

### CODE REVIEW

**Comment by niccholaspage** [comment]
I dunno if a /fe deduct command is really needed, I think that if you use /fe grant with a negative number might work but I'll have to test that out. The grant & set with shortened accounts seems like a good change, I'll probably merge that part if possible.

**Comment by OdiumxXx** [comment]
Granting someone a negative sum is constructing a counter intuitive UI, I urge you not to take that path.

The fact that the only way to deduct(Verb: Subtract or take away)  a sum from a player is by using the grant(Verb: Agree to give) command and a negative figure is both needless, and counter intuitive.

The addition has been written for you, and successfully tested on a live server.
I urge you not to reject an obvious improvement.

**Comment by niccholaspage** [comment]
I see what you mean but I don't want to add too much commands, it just seems kind of useless to have an extra command just for deducting money. I'll think about it.

**Comment by OdiumxXx** [comment]
Deducting money is a necessary feature which Fe is currently lacking.
It's hardly command-bloating to include a command which is both necessary and currently missing.

Nor is it 'useless' to provide a command for users to easily deduct money from a player.

EDIT:
At this point I want to specify that one of the reasons I like/d and use/d this plugin is because it isn't bloated with needless features like some of the others. However this is a necessary feature which it lacks.

**Pull request closed without merging**
