### PR TITLE
New superfast file database

### PR DESCRIPTION
**Pull request by CryLegend**
Hi,
Fe is a very good plugin, but it's unfortunately too slow. I've created a very fast file database which store accounts in file accounts.flat with model "player:money" like :
crylegend:1000.0
niccholaspage:1854.24

I load everything at the startup and I rewrite every 5 seconds in a separate thread if something changed. File writing perfs are very good: 300ms for 100000 accounts. Money operations are very fast, look at this benchmark: http://www.craftfriends.fr/Personnel/bench.png (1 transaction equals to +1 and -1)
SQLite perfs looks like 300ms for 25 transactions!

I hope this will contribute to this great plugin which allows me easely to integrate my own database.
Cordialy,

### CODE REVIEW

**Comment by CryLegend** [comment]
"GitHub pull request #30 to niccholaspage/Fe
Building remotely on s-7a63c959 in workspace /scratch/jenkins/workspace/niccholaspage/Fe
Checkout:Fe / /scratch/jenkins/workspace/niccholaspage/Fe - hudson.remoting.Channel@61109a3b:s-7a63c959
Using strategy: Build commits submitted for validated merge
Last Built Revision: Revision 3c5affbfc3321eb9a59267ca6c015e949a2408a2 (origin/master)
Cloning the remote Git repository
Cloning repository origin
Fetching upstream changes from git://github.com/niccholaspage/Fe.git
  Opening connection
    Done: 0
  Counting objects
    Done: 19
  Finding sources
    Done: 19
  Getting sizes
    Done: 3
  Compressing objects
    Done: 2
  Writing objects
    Done: 19
  remote: Resolving deltas
Merging refs/tags/changes/30
Commencing build of Revision ff3edbbffa0b2d12995c5908374f7b75dcb73bee (master)
Checking out Revision ff3edbbffa0b2d12995c5908374f7b75dcb73bee (master)
Could not record history. Previous build's commit, d6fc38c3a11cf11d915959643b768bcad1760e83, does not exist in the current repository.
[Fe] $ /usr/bin/tenant-isolate /bin/sh -xe /tmp/hudson1025390397029167892.sh
- ant
  Buildfile: build.xml does not exist!
  Build failed
  Build step 'Execute shell' marked build as failure
  Archiving artifacts
  Sending e-mails to: niccholaspage@gmail.com
  Putting comment on the pull request
  Finished: FAILURE"

I think your build system had a serious problem...

**Comment by niccholaspage** [comment]
Sorry, I'm in the middle of transferring to Maven which is why the build system is really failing. I might accept this PR but I really think I could make SQL faster too. I don't know yet, I'll think about it.

**Comment by niccholaspage** [comment]
Sorry, accidentally hit close..

**Comment by CryLegend** [comment]
No problem.
I think you're right but it's a new database, so the user has more choices.

**Comment by niccholaspage** [comment]
I dunno, I'll think about it, but first I'll try to make SQL faster.

**Comment by CryLegend** [comment]
Ok

**Comment by fensoft** [comment]
To add my little contribution, I think that
- you can't be faster than a hashmap
- sqlite is not designed to be ultra-fast (i.e. doing 1 000 000 different query)
- plain-file are more flexible for file-conversion

We've tried here with 1000 request: it takes 30 second using Fe+sqlite and few milliseconds with this patch' plain-file.
For some few events in my servers i have sometimes hundreds of Fe transactions per seconds and in this case it's lagging a lot.

**Comment by fensoft** [comment]
Hi,

Still no changes ? I'm stiff manualy patching Fe to add this patch to every version.
Having this in the master and release it should be better.

Regards,
fensoft

**Comment by niccholaspage** [comment]
I don't want you to need to manually patch Fe for every new commit. I've made some changes to Fe to allow you to add external databases. Look at this commit:
c56998810e95b019ff6ec39a3e083b226b566953

Now, you can load up a plugin before Fe and add a database in. Make a plugin and then in the plugin.yml, add the following options:

```
load: startup
loadbefore:
- Fe
```

Then in your plugin's onEnable, call Fe.getDatabases().add(database). This will let you add in your database which will then be used if the type is set in Fe's configuration.

**Comment by fensoft** [comment]
I think getDatabases() will return a copy, not a reference.
Maybe adding Fe.addDatabase(database) will be better ?

**Comment by niccholaspage** [comment]
Yeah - you're right. Changed in this commit:
95830cc0af02ce7b93fbc835578c1d71fae1120d

**Comment by CryLegend** [comment]
Good, good. Thank you bro.

**Pull request closed without merging**
